### ISSUE TITLE
Trailing Delimiters (or a mapping must have a field and not a delimiter as the last element)

### ISSUE THREAD

**Issue by tomrade** [logstash-plugins/logstash-filter-dissect#22]
More of  question, but I when I was testing replacing my apache combined/common grok lines with dissect I had to add an empty match %{} onto the end of the mapping otherwise the last double quote (") would appear in the useragent. Is this the desired behaviour for dissect?

Mapping
%{clientIP} %{rfcIdent} %{userName} [%{timestamp} %{+timestamp}] "%{method} %{uriStem} HTTP/%{httpVersion}" %{responseCode} %{bytesRecv} "%{referrer}" "%{userAgent}"%{}

**Comment by jordansissel** [comment]
I don't think adding `%{}` at the end should be necessary (it's certainly confusing and unexpected).

Can you show me a sample log?

**Comment by tomrade** [comment]
The exact line I used. (I only had common logs so added the extra fields for testing) after a bit of thinking is it related to the fact there is a space in the useragent? so the filter is appending the leftovers to the useragent

192.168.2.46 - - [13/Apr/2017:15:30:10 +0000] "POST http://urlquery.net/api/v2/post.php HTTP/1.1" 503 3903 "ref" "user agent"

With empty match at end 
"userAgent" => "user agent",

Without empty match at end
"userAgent" => "user agent\""

**Comment by guyboertje** [comment]
@tomrade @jordansissel 
This is by design. One can say that dissect is delimiter centric and grok is value centric. The definition of a delimiter is all the characters between `}` and `%{` so unless the last double quote is between `}` and `%{` it is not detected and treated as a delimiter - its just part of the rest. The rest being defined as what ever was found after the last **known** delimiter.

Adding the trailing %{} at the end, while inelegant, is really a noop because no more text is found as an offset and length so no strings are created in the skip field.

_On the other hand, perhaps it is handy to capture the rest and test for it later (in a file output say) so you get a heads-up if some unexpected trailing text is added in the future. For example, a field suddenly contains an unexpected delimiter in it - all the values after it will be moved right and the 'rest' field will not be empty. For example, a URL that has not been encoded correctly or has a search term that contains the next delimiter `" `. You should dev test for this a see how the event fields/values change and maybe add a conditional to warn you._

Dissect is designed to work where both the line is highly structured and semi structured.
Semi-structured, where the first section of a line is structured and a 'rest' or 'remainder' that is the variable section - invariably the 'message', in this semi-structured case the last `%{msg}` captures the rest.
Highly structured is viewed more like a CSV where there is a first and last value with delimiters separating values in between those two.

I am leaving this issue open for a while so others can find it easily.

**Comment by guyboertje** [comment]
I decided to relax this requirement. However, the delimiter detection is now stricter - meaning a no match results if every delimiter is not found in exactly the declared order.
