### ISSUE TITLE
delimiter is added to the value of the field

### ISSUE THREAD

**Issue by yarko686** [logstash-plugins/logstash-filter-dissect#63]
I am using logstash 6.3.0 on CentOS 7
My config looks like this
```
filter {
    dissect {
        mapping => {
            'message' => '%{time} %{request_time} %{} action(field1=%{field1}, field2=%{field2}, field3=%{field3})'
        }
    }
}
```

The issue is that no matter what I do and how do i place the brackets ( and ), this one ) is always attached to the field3. So in the output I see field3 => "value3)" instead of field3 => "value3"

**Comment by guyboertje** [comment]
@yarko686 

The docs say...

> This is repeated for each field/# delimiter pair thereafter until the last delimiter is reached, then the remaining text is stored in the last field.

The plugin does not know that the closing `)` is a delimiter. The left most field is a special case where it does not have to have a delimiter on its left hand side.

A delimiter is identified from the mapping pattern by having `%{` to the right hand side of it.

If you need the `)` to be seen as a delimiter and not the "rest" of the line - add a skip field at the very end, e.g. `field3=%{field3})%{}`.

It is designed this way because, more often than not, a log line has more of its meaningful data on the left side of the line - I tried to make it easier to extract those fields and assign the "rest" to the last field.

**Comment by yarko686** [comment]
@guyboertje thank you, everything is working now.
